name: video_player
description: Video player for MacOS 
repository: https://github.com/flutter/plugins/tree/main/packages/video_player/video_player
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.5.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      macos:
        default_package: video_player_macos

dependencies:
  flutter:
    sdk: flutter
  video_player_macos: ^1.0.6
  video_player_platform_interface: ">=5.1.1 <7.0.0"
